---
title: "Script Mattheus 2.0"
author: "Gijs Custers"
date: "7 juli 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### load relevant packages


rm(list = ls())

library(Hmisc)
library(tidyverse)
library(foreign)
library(car)
library(weights)
library(reshape2)
library(Matrix)
library(lme4)
library(influence.ME)
library(rockchalk)
library(dummies)


##list variables: Age, Gender, Household, Ethnicity, Tenure, Adress_years,Neigh_responsibility, Neighb_involve, Contact_neighbours, Contact_othernei, Neigh_familiarity, Neigh_joy_int, Neigh_cosy, Neigh_feelhome, Neigh_notnice, Neigh_move, Neigh_lucky, Neigh_treat, Neigh_attitudes, Neigh_youngold, Neigh_problemsother, Neigh_problem, Municipality_support, Neigh_attachment, Labour_status, Volunteering, Dutch_read, Dutch_speak, Dutch_write, Health, Education,  Wijk71,	Low_40, Disposable_income,	Perc_unemployed,	Perc_benefits,	Herf_div, Turnover


```

Load data and select relevant variables, 2008 (base dataset)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

##### contact met buren toevoegen??#### kan gesynchroniseerd worden...2008-2010 met 2011-2015

## load raw data 2008 (WAVEID = ....(year).....(respondent#))

data2008 <- read.spss("C:/Data Mattheus 2.0/Sociale Index enquete 2008 edit.sav", use.value.labels = FALSE, to.data.frame = TRUE)

#### select relevant variables, based on "Overzicht variabelen waves Wijkprofiel v2.xlsx"

data2008sel <- data2008 %>% select(v1, v2, v3a, etni, v9, v12d, v13, v14a_1, v14a_2, v14a_3, v16, v17, v18a, v18b, v18c, v18d, v18e, v18f, v18g, v18h, v18i, v18j, v18k, v18l, v23b, v24a, v28, v29a, v33, v48a, v48b, v48c, v49, v55a, buurt, ijssel, GEWICHT_STAD, WAVEID, WAVE)

### recode and rename variables ###

##Gender
data2008sel$v2[data2008sel$v2==2] <- 0
v2_labels <- c("Female", "Male")
data2008sel$v2 <- factor(data2008sel$v2, labels = v2_labels, ordered = FALSE)

##Household
data2008sel$v3a <- recode(data2008sel$v3a, "5:12 = 5; 97:98=NA")
v3a_labels <- c("SingleHH","Couplenochild","Couplechild","SingleparentHH","Other")
data2008sel$v3a <- factor(data2008sel$v3a, labels = v3a_labels, ordered = FALSE)

##Ethnicity
etni_labels <- c("Dutch", "Turkish", "Moroccan","Antillean", "Surinamese", "Cape-Verdean","Other")
data2008sel$etni <- factor(data2008sel$etni, labels = etni_labels, ordered = FALSE)

##Tenure
data2008sel$v9 <-recode(data2008sel$v9, "3=99;2=1;1=0;NA=99")
v9_labels <- c("Rent", "Owner","Missing")
data2008sel$v9 <- factor(data2008sel$v9, labels = v9_labels, ordered = FALSE)

##Neigh_responsibility
data2008sel$v13 <- recode(data2008sel$v13, "2:3=2;4:5=3")
data2008sel$v13[data2008sel$v13==6]<- 4
data2008sel$v13[is.na(data2008sel$v13)]<- 4
v13_labels <- c("Ja heel erg","Ja een beetje","Niet","Weet niet")
data2008sel$v13 <- factor(data2008sel$v13, labels = v13_labels, ordered = FALSE)

##Neighb_involve
data2008sel$v14a_1R <- recode(data2008sel$v14a_1, "5=0; 1:3=1")
v14a_1_labels <- c("No", "Yes")
data2008sel$v14a_1R <- factor(data2008sel$v14a_1R, labels = v14a_1_labels, ordered = FALSE)

#countvariable Neighb_involvement
data2008sel$v14a_1count <- recode(data2008sel$v14a_1, "5=0; 1:3=1")
data2008sel$v14a_2count <- recode(data2008sel$v14a_2, "1:3=1; NA=0")
data2008sel$v14a_3count <- recode(data2008sel$v14a_3, "1:3=1; NA=0")

data2008sel$Count_involve <- data2008sel$v14a_1count + data2008sel$v14a_2count + data2008sel$v14a_3count 

##Contact_neighbours
data2008sel$v16 <- 5 - data2008sel$v16

##Contact_othernei
data2008sel$v17 <- 5 - data2008sel$v17

## coding positive responses neighbourhood cohesion
#Neigh_familiarity (0=helemaal mee eens ... 4=helemaal mee oneens)
data2008sel$v18a[data2008sel$v18a==6] <- NA
data2008sel$v18a <- data2008sel$v18a - 1

#Neigh_joy_int (0=helemaal mee oneens ... 4=helemaal mee eens)
data2008sel$v18b[data2008sel$v18b==6] <- NA
data2008sel$v18b <- 5 - data2008sel$v18b

#Neigh_cosy
data2008sel$v18c[data2008sel$v18c==6] <- NA
data2008sel$v18c <- 5 - data2008sel$v18c

#Neigh_feelhome
data2008sel$v18d[data2008sel$v18d==6] <- NA
data2008sel$v18d <- 5 - data2008sel$v18d

#Neigh_notnice
data2008sel$v18e[data2008sel$v18e==6] <- NA
data2008sel$v18e <- data2008sel$v18e - 1

#Neigh_move
data2008sel$v18f[data2008sel$v18f==6] <- NA
data2008sel$v18f <- data2008sel$v18f - 1

#Neigh_lucky
data2008sel$v18g[data2008sel$v18g==6] <- NA
data2008sel$v18g <- 5 - data2008sel$v18g

#Neigh_treat
data2008sel$v18h[data2008sel$v18h==6] <- NA
data2008sel$v18h <- data2008sel$v18h - 1

#Neigh_attitudes
data2008sel$v18i[data2008sel$v18i==6] <- NA
data2008sel$v18i <- 5 - data2008sel$v18i

#Neigh_youngold
data2008sel$v18j[data2008sel$v18j==6] <- NA
data2008sel$v18j <- 5 - data2008sel$v18j

#Neigh_problemsother
data2008sel$v18k[data2008sel$v18k==6] <- NA
data2008sel$v18k <- data2008sel$v18k - 1

#Neigh_problem
data2008sel$v18l[data2008sel$v18l==6] <- NA
data2008sel$v18l <- data2008sel$v18l - 1

##Municipality_support
v23b_labels <- c("H mee eens", "mee eens","eens/oneens","mee oneens","h mee oneens","weet niet")
data2008sel$v23b <- factor(data2008sel$v23b, labels = v23b_labels, ordered = FALSE)

##Neigh_attachment
data2008sel$v24a[data2008sel$v24a==6] <- NA
data2008sel$v24a <- data2008sel$v24a - 1

##Labour_status
data2008sel$Labour_status[data2008sel$v28==1] <- 1
data2008sel$Labour_status[data2008sel$v29a==3] <- 2
data2008sel$Labour_status[data2008sel$v29a==1] <- 3
data2008sel$Labour_status[data2008sel$v29a==2] <- 4
data2008sel$Labour_status[data2008sel$v29a==4] <- 5
data2008sel$Labour_status[data2008sel$v29a==7 | data2008sel$v29a==8] <- 6
data2008sel$Labour_status[data2008sel$v29a==6] <- 99
data2008sel$Labour_status[is.na(data2008sel$Labour_status)] <- 99 

Labour_labels <- c("Works>12h","Unemployed/incapacitated","Student","Household","Retired", "Volunteer/Other","Missing")
data2008sel$Labour_status <- factor(data2008sel$Labour_status, labels = Labour_labels, ordered = FALSE) 

##Volunteering
data2008sel$v33[data2008sel$v33==2] <- 0

##Dutch language
data2008sel$v48a <- data2008sel$v48a - 1 
data2008sel$v48b <- data2008sel$v48b - 1
data2008sel$v48c <- data2008sel$v48c - 1

##Health
data2008sel$v49 <- 5 - data2008sel$v49

##Education
data2008sel$Educ_interval <- data2008sel$v55a
data2008sel$Educ_interval[data2008sel$v55a==10] <- NA 
data2008sel$Educ_interval <- recode(data2008sel$Educ_interval,"3:4=3;5=4;6=5;7=6;8=7")

data2008sel$Educ_ordinal <- recode(data2008sel$Educ_interval,"0:1=0;2:3=1;4:5=2;6:7=3;NA=99")

Educ_labels <- c("Low","Low-med","Medium","High", "Missing")
data2008sel$Educ_ordinal <- factor(data2008sel$Educ_ordinal, labels = Educ_labels, ordered = FALSE)

## Neighbourhood (excl. Rozenburg[4]/Kop van Zuid[17])

data2008sel$Wijk71 <- data2008sel$buurt
data2008sel$Wijk71 <- recode(data2008sel$buurt, "2:3=3001;18:19=3003;27:28=3004")
data2008sel$Wijk71[data2008sel$buurt==32 | data2008sel$buurt==58] <- 3011
data2008sel$Wijk71[data2008sel$buurt==42 | data2008sel$buurt==43] <- 3005
data2008sel$Wijk71[data2008sel$buurt==52 | data2008sel$buurt==54 | data2008sel$buurt==55 | data2008sel$buurt==57] <- 3006
data2008sel$Wijk71[data2008sel$ijssel==1] <- 1009
data2008sel$Wijk71[data2008sel$ijssel==2] <- 1010

#variable names recoding
data2008sel <- data2008sel %>% rename(Age = v1, Male = v2, Household = v3a, Ethnicity = etni, Tenure = v9,
                                      Adress_years = v12d, Neigh_responsibility = v13, Neigh_involve = v14a_1R, Contact_neighbours = v16, Contact_othernei = v17, Neigh_familiarity = v18a, Neigh_joy_int = v18b, Neigh_cosy = v18c, Neigh_feelhome = v18d, Neigh_notnice = v18e, Neigh_move=v18f, Neigh_lucky=v18g,Neigh_treat=v18h,Neigh_attitudes=v18i,Neigh_youngold=v18j,Neigh_problemsother=v18k,Neigh_problem = v18l, Municipality_support = v23b, Neigh_attachment=v24a,Volunteering = v33, Dutch_read = v48a, Dutch_speak = v48b, Dutch_write = v48c, Health = v49)

##original variables that need to be dropped 

data2008seldef <- subset(data2008sel, select = -c(buurt,ijssel,v55a,v28,v29a,v14a_1,v14a_2,v14a_3,v14a_1count,v14a_2count,v14a_3count))


### adding contextual variables.

## missing values: 1[Low_40], 4[Perc_unemployed,Perc_benefits, Herf_div]
# replaced by 1[Low40(2009)], 4[Perc_unemployed(2011),Perc_benefits(2013), Herf_div(2011)]

Context2008 <- read.csv("C:/Data Mattheus 2.0/Buurtdata context 2008 - Adj.csv", sep = ";")
data2008seldef <- inner_join(data2008seldef, Context2008)


```

Data preparation 2009

``` {r setup, include = FALSE}

##load raw data 2009
data2009 <- read.spss("C:/Data Mattheus 2.0/Sociale Index enquete 2009 edit.sav", use.value.labels = FALSE, to.data.frame = TRUE)

##selection relevant variables
data2009sel <- data2009 %>% select(v1, v2, v3a, etni, v9, v12d, v13, v14a_1, v14a_2, v14a_3, v16, v17, v18a, v18b, v18c, v18d, v18e, v18f, v18g, v18h, v18i, v18j, v18k, v18l, v23b, v24a, v28, v29a, v33, v48a, v48b, v48c, v49, v55a, buurt, ijssel, GEWICHT_STAD, WAVEID, WAVE)

##Gender
data2009sel$v2[data2009sel$v2==2] <- 0
data2009sel$v2 <- factor(data2009sel$v2, labels = v2_labels, ordered = FALSE)

##Household
data2009sel$v3a <- recode(data2009sel$v3a, "5:12 = 5")
data2009sel$v3a <- factor(data2009sel$v3a, labels = v3a_labels, ordered = FALSE)

##Ethnicity
data2009sel$etni <- factor(data2009sel$etni, labels = etni_labels, ordered = FALSE)

##Tenure
data2009sel$v9 <-recode(data2009sel$v9, "3=99;2=1;1=0;NA=99")
data2009sel$v9 <- factor(data2009sel$v9, labels = v9_labels, ordered = FALSE)

##Neigh_responsibility
data2009sel$v13 <- recode(data2009sel$v13, "2:3=2;4:5=3")
data2009sel$v13[data2009sel$v13==6]<- 4
data2009sel$v13[is.na(data2009sel$v13)]<- 4
data2009sel$v13 <- factor(data2009sel$v13, labels = v13_labels, ordered = FALSE)

##Neighb_involve
data2009sel$v14a_1R <- recode(data2009sel$v14a_1, "5=0; 1:4=1")
data2009sel$v14a_1R <- factor(data2009sel$v14a_1R, labels = v14a_1_labels, ordered = FALSE)

#countvariable Neighb_involvement
data2009sel$v14a_1count <- recode(data2009sel$v14a_1, "5=0; 1:4=1")
data2009sel$v14a_2count <- recode(data2009sel$v14a_2, "1:3=1; NA=0")
data2009sel$v14a_3count <- recode(data2009sel$v14a_3, "1:3=1; NA=0")

data2009sel$Count_involve <- data2009sel$v14a_1count + data2009sel$v14a_2count + data2009sel$v14a_3count 

##Contact_neighbours
data2009sel$v16 <- 5 - data2009sel$v16

##Contact_othernei
data2009sel$v17 <- 5 - data2009sel$v17

## coding positive responses neighbourhood cohesion
#Neigh_familiarity (0=helemaal mee eens ... 4=helemaal mee oneens)
data2009sel$v18a[data2009sel$v18a==6] <- NA
data2009sel$v18a <- data2009sel$v18a - 1

#Neigh_joy_int (0=helemaal mee oneens ... 4=helemaal mee eens)
data2009sel$v18b[data2009sel$v18b==6] <- NA
data2009sel$v18b <- 5 - data2009sel$v18b

#Neigh_cosy
data2009sel$v18c[data2009sel$v18c==6] <- NA
data2009sel$v18c <- 5 - data2009sel$v18c

#Neigh_feelhome
data2009sel$v18d[data2009sel$v18d==6] <- NA
data2009sel$v18d <- 5 - data2009sel$v18d

#Neigh_notnice
data2009sel$v18e[data2009sel$v18e==6] <- NA
data2009sel$v18e <- data2009sel$v18e - 1

#Neigh_move
data2009sel$v18f[data2009sel$v18f==6] <- NA
data2009sel$v18f <- data2009sel$v18f - 1

#Neigh_lucky
data2009sel$v18g[data2009sel$v18g==6] <- NA
data2009sel$v18g <- 5 - data2009sel$v18g

#Neigh_treat
data2009sel$v18h[data2009sel$v18h==6] <- NA
data2009sel$v18h <- data2009sel$v18h - 1

#Neigh_attitudes
data2009sel$v18i[data2009sel$v18i==6] <- NA
data2009sel$v18i <- 5 - data2009sel$v18i

#Neigh_youngold
data2009sel$v18j[data2009sel$v18j==6] <- NA
data2009sel$v18j <- 5 - data2009sel$v18j

#Neigh_problemsother
data2009sel$v18k[data2009sel$v18k==6] <- NA
data2009sel$v18k <- data2009sel$v18k - 1

#Neigh_problem
data2009sel$v18l[data2009sel$v18l==6] <- NA
data2009sel$v18l <- data2009sel$v18l - 1

##Municipality_support
data2009sel$v23b <- factor(data2009sel$v23b, labels = v23b_labels, ordered = FALSE)

##Neigh_attachment
data2009sel$v24a[data2009sel$v24a==6] <- NA
data2009sel$v24a <- data2009sel$v24a - 1

##Labour_status
data2009sel$Labour_status[data2009sel$v28==1] <- 1
data2009sel$Labour_status[data2009sel$v29a==3] <- 2
data2009sel$Labour_status[data2009sel$v29a==1] <- 3
data2009sel$Labour_status[data2009sel$v29a==2] <- 4
data2009sel$Labour_status[data2009sel$v29a==4] <- 5
data2009sel$Labour_status[data2009sel$v29a==7 | data2009sel$v29a==8] <- 6
data2009sel$Labour_status[data2009sel$v29a==6] <- 99
data2009sel$Labour_status[is.na(data2009sel$Labour_status)] <- 99 

data2009sel$Labour_status <- factor(data2009sel$Labour_status, labels = Labour_labels, ordered = FALSE) 

##Volunteering
data2009sel$v33[data2009sel$v33==2] <- 0

##Dutch language
data2009sel$v48a <- data2009sel$v48a - 1 
data2009sel$v48b <- data2009sel$v48b - 1
data2009sel$v48c <- data2009sel$v48c - 1

##Health
data2009sel$v49 <- 5 - data2009sel$v49

##Education
data2009sel$Educ_interval <- data2009sel$v55a
data2009sel$Educ_interval[data2009sel$v55a==10] <- NA 
data2009sel$Educ_interval <- recode(data2009sel$Educ_interval,"3:4=3;5=4;6=5;7=6;8=7")

data2009sel$Educ_ordinal <- recode(data2009sel$Educ_interval,"0:1=0;2:3=1;4:5=2;6:7=3;NA=99")
data2009sel$Educ_ordinal <- factor(data2009sel$Educ_ordinal, labels = Educ_labels, ordered = FALSE)

## Neighbourhood:Wijk71 (excl. Rozenburg[4])

data2009sel$Wijk71 <- data2009sel$buurt
data2009sel$Wijk71 <- recode(data2009sel$buurt, "2:3=3001;18:19=3003;27:28=3004")
data2009sel$Wijk71[data2009sel$buurt==32 | data2009sel$buurt==58] <- 3011
data2009sel$Wijk71[data2009sel$buurt==42 | data2009sel$buurt==43] <- 3005
data2009sel$Wijk71[data2009sel$buurt==52 | data2009sel$buurt==54 | data2009sel$buurt==55 | data2009sel$buurt==57] <- 3006
data2009sel$Wijk71[data2009sel$ijssel==1] <- 1009
data2009sel$Wijk71[data2009sel$ijssel==2] <- 1010

##variable names recoding
data2009sel <- data2009sel %>% rename(Age = v1, Male = v2, Household = v3a, Ethnicity = etni, Tenure = v9,
                                      Adress_years = v12d, Neigh_responsibility = v13, Neigh_involve = v14a_1R,Contact_neighbours = v16, Contact_othernei = v17,  Neigh_familiarity = v18a, Neigh_joy_int = v18b, Neigh_cosy = v18c, Neigh_feelhome = v18d, Neigh_notnice = v18e, Neigh_move=v18f, Neigh_lucky=v18g,Neigh_treat=v18h,Neigh_attitudes=v18i,Neigh_youngold=v18j,Neigh_problemsother=v18k,Neigh_problem = v18l, Municipality_support = v23b, Neigh_attachment=v24a,Volunteering = v33, Dutch_read = v48a, Dutch_speak = v48b, Dutch_write = v48c, Health = v49)

##original variables that need to be dropped 

data2009seldef <- subset(data2009sel, select = -c(buurt,ijssel,v55a,v28,v29a,v14a_1,v14a_2,v14a_3,v14a_1count,v14a_2count,v14a_3count))

### adding contextual variables.

## missing values: 3005[Low_40,Disposable_income], 4[Perc_unemployed,Perc_benefits, Herf_div]
# replaced by 3005[Low_40(2010),Disposable_income(2010)], 4[Perc_unemployed(2011),Perc_benefits(2013), Herf_div(2011)]

Context2009 <- read.csv("C:/Data Mattheus 2.0/Buurtdata context 2009 - Adj.csv", sep = ";")
data2009seldef <- inner_join(data2009seldef, Context2009)

```

Data preparation 2010

``` {r setup, include=FALSE}

##load raw data 2010
data2010 <- read.spss("C:/Data Mattheus 2.0/Sociale Index enquete 2010 edit.sav", use.value.labels = FALSE, to.data.frame = TRUE)

##selection relevant variables
data2010sel <- data2010 %>% select(v1, v2, v3a, etni, v9, v12d, v13, v14a_1, v14a_2, v14a_3, v16, v17, v18a, v18b, v18c, v18d, v18e, v18f, v18g, v18h, v18i, v18j, v18k, v18l, v23b, v24a, v28, v29a, v33, v48a, v48b, v48c, v49, v55a, buurt, ijssel, GEWICHT_STAD, WAVEID, WAVE)

##Gender
data2010sel$v2[data2010sel$v2==2] <- 0
data2010sel$v2 <- factor(data2010sel$v2, labels = v2_labels, ordered = FALSE)

##Household
data2010sel$v3a <- recode(data2010sel$v3a, "5:12 = 5")
data2010sel$v3a <- factor(data2010sel$v3a, labels = v3a_labels, ordered = FALSE)

##Ethnicity
data2010sel$etni <- factor(data2010sel$etni, labels = etni_labels, ordered = FALSE)

##Tenure
data2010sel$v9 <-recode(data2010sel$v9, "3=99;2=1;1=0;NA=99")
data2010sel$v9 <- factor(data2010sel$v9, labels = v9_labels, ordered = FALSE)

##Neigh_responsibility
data2010sel$v13[is.na(data2010sel$v13)]<- 4
data2010sel$v13 <- factor(data2010sel$v13, labels = v13_labels, ordered = FALSE)

##Neighb_involve
data2010sel$v14a_1R <- recode(data2010sel$v14a_1, "5=0; 1:3=1")
data2010sel$v14a_1R <- factor(data2010sel$v14a_1R, labels = v14a_1_labels, ordered = FALSE)

#countvariable Neighb_involvement
data2010sel$v14a_1count <- recode(data2010sel$v14a_1, "5=0; 1:4=1")
data2010sel$v14a_2count <- recode(data2010sel$v14a_2, "1:3=1; NA=0")
data2010sel$v14a_3count <- recode(data2010sel$v14a_3, "1:3=1; NA=0")

data2010sel$Count_involve <- data2010sel$v14a_1count + data2010sel$v14a_2count + data2010sel$v14a_3count

##Contact_neighbours
data2010sel$v16 <- 5 - data2010sel$v16

##Contact_othernei
data2010sel$v17 <- 5 - data2010sel$v17

## coding positive responses neighbourhood cohesion
#Neigh_familiarity (0=helemaal mee eens ... 4=helemaal mee oneens)
data2010sel$v18a[data2010sel$v18a==6] <- NA
data2010sel$v18a <- data2010sel$v18a - 1

#Neigh_joy_int (0=helemaal mee oneens ... 4=helemaal mee eens)
data2010sel$v18b[data2010sel$v18b==6] <- NA
data2010sel$v18b <- 5 - data2010sel$v18b

#Neigh_cosy
data2010sel$v18c[data2010sel$v18c==6] <- NA
data2010sel$v18c <- 5 - data2010sel$v18c

#Neigh_feelhome
data2010sel$v18d[data2010sel$v18d==6] <- NA
data2010sel$v18d <- 5 - data2010sel$v18d

#Neigh_notnice
data2010sel$v18e[data2010sel$v18e==6] <- NA
data2010sel$v18e <- data2010sel$v18e - 1

#Neigh_move
data2010sel$v18f[data2010sel$v18f==6] <- NA
data2010sel$v18f <- data2010sel$v18f - 1

#Neigh_lucky
data2010sel$v18g[data2010sel$v18g==6] <- NA
data2010sel$v18g <- 5 - data2010sel$v18g

#Neigh_treat
data2010sel$v18h[data2010sel$v18h==6] <- NA
data2010sel$v18h <- data2010sel$v18h - 1

#Neigh_attitudes
data2010sel$v18i[data2010sel$v18i==6] <- NA
data2010sel$v18i <- 5 - data2010sel$v18i

#Neigh_youngold
data2010sel$v18j[data2010sel$v18j==6] <- NA
data2010sel$v18j <- 5 - data2010sel$v18j

#Neigh_problemsother
data2010sel$v18k[data2010sel$v18k==6] <- NA
data2010sel$v18k <- data2010sel$v18k - 1

#Neigh_problem
data2010sel$v18l[data2010sel$v18l==6] <- NA
data2010sel$v18l <- data2010sel$v18l - 1

##Municipality_support
data2010sel$v23b <- factor(data2010sel$v23b, labels = v23b_labels, ordered = FALSE)

##Neigh_attachment
data2010sel$v24a[data2010sel$v24a==6] <- NA
data2010sel$v24a <- data2010sel$v24a - 1

##Labour_status
data2010sel$Labour_status[data2010sel$v28==1] <- 1
data2010sel$Labour_status[data2010sel$v29a==3] <- 2
data2010sel$Labour_status[data2010sel$v29a==1] <- 3
data2010sel$Labour_status[data2010sel$v29a==2] <- 4
data2010sel$Labour_status[data2010sel$v29a==4] <- 5
data2010sel$Labour_status[data2010sel$v29a==7 | data2010sel$v29a==8] <- 6
data2010sel$Labour_status[data2010sel$v29a==6] <- 99
data2010sel$Labour_status[is.na(data2010sel$Labour_status)] <- 99 

data2010sel$Labour_status <- factor(data2010sel$Labour_status, labels = Labour_labels, ordered = FALSE) 

##Volunteering
data2010sel$v33[data2010sel$v33==2] <- 0

##Dutch language
data2010sel$v48a <- data2010sel$v48a - 1 
data2010sel$v48b <- data2010sel$v48b - 1
data2010sel$v48c <- data2010sel$v48c - 1

##Health
data2010sel$v49 <- 5 - data2010sel$v49

##Education
data2010sel$Educ_interval <- data2010sel$v55a
data2010sel$Educ_interval[data2010sel$v55a==10] <- NA 
data2010sel$Educ_interval <- recode(data2010sel$Educ_interval,"3:4=3;5=4;6=5;7=6;8=7")

data2010sel$Educ_ordinal <- recode(data2010sel$Educ_interval,"0:1=0;2:3=1;4:5=2;6:7=3;NA=99")
data2010sel$Educ_ordinal <- factor(data2010sel$Educ_ordinal, labels = Educ_labels, ordered = FALSE)

## Neighbourhood:Wijk71 (excl. Rozenburg[4 of 0?]). Check ijssel==2 in SPSS-file
data2010sel$Wijk71 <- data2010sel$buurt
data2010sel$Wijk71 <- recode(data2010sel$buurt, "2:3=3001;18:19=3003;27:28=3004")
data2010sel$Wijk71[data2010sel$buurt==32 | data2010sel$buurt==58] <- 3011
data2010sel$Wijk71[data2010sel$buurt==42 | data2010sel$buurt==43] <- 3005
data2010sel$Wijk71[data2010sel$buurt==52 | data2010sel$buurt==54 | data2010sel$buurt==55 | data2010sel$buurt==57] <- 3006
data2010sel$Wijk71[data2010sel$ijssel==1] <- 1009
data2010sel$Wijk71[data2010sel$ijssel==2] <- 1010

#variable names recoding
data2010sel <- data2010sel %>% rename(Age = v1, Male = v2, Household = v3a, Ethnicity = etni, Tenure = v9, Adress_years = v12d, Neigh_responsibility = v13, Neigh_involve = v14a_1R,Contact_neighbours = v16, Contact_othernei = v17,  Neigh_familiarity = v18a, Neigh_joy_int = v18b, Neigh_cosy = v18c, Neigh_feelhome = v18d, Neigh_notnice = v18e, Neigh_move=v18f, Neigh_lucky=v18g,Neigh_treat=v18h,Neigh_attitudes=v18i,Neigh_youngold=v18j,Neigh_problemsother=v18k,Neigh_problem = v18l, Municipality_support = v23b, Neigh_attachment=v24a,Volunteering = v33, Dutch_read = v48a, Dutch_speak = v48b, Dutch_write = v48c, Health = v49)

##original variables that need to be dropped 

data2010seldef <- subset(data2010sel, select = -c(buurt,ijssel,v55a,v28,v29a,v14a_1,v14a_2,v14a_3,v14a_1count,v14a_2count,v14a_3count))

### adding contextual variables.

## missing values:4[Perc_unemployed,Perc_benefits, Herf_div]
# replaced by 4[Perc_unemployed(2011),Perc_benefits(2013), Herf_div(2011)]

Context2010 <- read.csv("C:/Data Mattheus 2.0/Buurtdata context 2010 - Adj.csv", sep = ";")
data2010seldef <- inner_join(data2010seldef, Context2010)

```

Data preparation 2011

``` {r setup, include = FALSE}

##Adress_years => BRP?? Ask Dick

##load raw data 2011
data2011 <- read.spss("C:/Data Mattheus 2.0/Sociale Index enquete 2011 nieuwe versie edit.sav", use.value.labels = FALSE, to.data.frame = TRUE)

##select relevant variables
data2011sel <- data2011 %>% select(v1, v2, v3a, st_etni, v10, v18, v19a_1, v19a_2, v19a_3, v42c,v42d, v22a, v22b, v22c, v22d, v22e, v22f, v22g, v22h, v22i, v22j, v22k, v22l, v27b, v28a, v34, v35a, v37, v51a, v51b, v51c, v53, v62a, gebcode, GEWICHT_STAD, WAVEID, WAVE)

##Gender
data2011sel$v2[data2011sel$v2==2] <- 0
data2011sel$v2 <- factor(data2011sel$v2, labels = v2_labels, ordered = FALSE)

##Household
data2011sel$v3a <- recode(data2011sel$v3a, "5:12 = 5")
data2011sel$v3a <- factor(data2011sel$v3a, labels = v3a_labels, ordered = FALSE)

##Ethnicity
data2011sel$st_etni <- recode(data2011sel$st_etni, "7=1;4=2;5=3;2=4;1=5;3=6;6=7;12=7")
data2011sel$st_etni <- factor(data2011sel$st_etni, labels = etni_labels, ordered = FALSE)

##Tenure
data2011sel$v10 <-recode(data2011sel$v10, "3=99;2=0;NA=99")
data2011sel$v10 <- factor(data2011sel$v10, labels = v9_labels, ordered = FALSE)

##Neigh_responsibility
data2011sel$v18[is.na(data2011sel$v18)]<- 4
data2011sel$v18 <- factor(data2011sel$v18, labels = v13_labels, ordered = FALSE)

##Neighb_involve
data2011sel$v19a_1R <- recode(data2011sel$v19a_1, "5=0; 1:3=1")
data2011sel$v19a_1R <- factor(data2011sel$v19a_1R, labels = v14a_1_labels, ordered = FALSE)

#countvariable Neighb_involvement
data2011sel$v19a_1count <- recode(data2011sel$v19a_1, "5=0; 1:4=1")
data2011sel$v19a_2count <- recode(data2011sel$v19a_2, "1:3=1; NA=0")
data2011sel$v19a_3count <- recode(data2011sel$v19a_3, "1:3=1; NA=0")

data2011sel$Count_involve <- data2011sel$v19a_1count + data2011sel$v19a_2count + data2011sel$v19a_3count

##Contact_neighbours
data2011sel$v42c <- recode(data2011sel$v42c, "1:2=2")
data2011sel$v42c <- 6 - data2011sel$v42c

##Contact_othernei
data2011sel$v42d <- recode(data2011sel$v42d, "1:2=2")
data2011sel$v42d <- 6 - data2011sel$v42d

## coding positive responses neighbourhood cohesion
#Neigh_familiarity (0=helemaal mee eens ... 4=helemaal mee oneens)
data2011sel$v22a[data2011sel$v22a==6] <- NA
data2011sel$v22a <- data2011sel$v22a - 1

#Neigh_joy_int (0=helemaal mee oneens ... 4=helemaal mee eens)
data2011sel$v22b[data2011sel$v22b==6] <- NA
data2011sel$v22b <- 5 - data2011sel$v22b

#Neigh_cosy
data2011sel$v22c[data2011sel$v22c==6] <- NA
data2011sel$v22c <- 5 - data2011sel$v22c

#Neigh_feelhome
data2011sel$v22d[data2011sel$v22d==6] <- NA
data2011sel$v22d <- 5 - data2011sel$v22d

#Neigh_notnice
data2011sel$v22e[data2011sel$v22e==6] <- NA
data2011sel$v22e <- data2011sel$v22e - 1

#Neigh_move
data2011sel$v22f[data2011sel$v22f==6] <- NA
data2011sel$v22f <- data2011sel$v22f - 1

#Neigh_lucky
data2011sel$v22g[data2011sel$v22g==6] <- NA
data2011sel$v22g <- 5 - data2011sel$v22g

#Neigh_treat
data2011sel$v22h[data2011sel$v22h==6] <- NA
data2011sel$v22h <- data2011sel$v22h - 1

#Neigh_attitudes
data2011sel$v22i[data2011sel$v22i==6] <- NA
data2011sel$v22i <- 5 - data2011sel$v22i

#Neigh_youngold
data2011sel$v22j[data2011sel$v22j==6] <- NA
data2011sel$v22j <- 5 - data2011sel$v22j

#Neigh_problemsother
data2011sel$v22k[data2011sel$v22k==6] <- NA
data2011sel$v22k <- data2011sel$v22k - 1

#Neigh_problem
data2011sel$v22l[data2011sel$v22l==6] <- NA
data2011sel$v22l <- data2011sel$v22l - 1

##Municipality_support
data2011sel$v27b <- factor(data2011sel$v27b, labels = v23b_labels, ordered = FALSE)

##Neigh_attachment
data2011sel$v28a[data2011sel$v28a==6] <- NA
data2011sel$v28a <- data2011sel$v28a - 1

##Labour_status
data2011sel$Labour_status[data2011sel$v34==2] <- 1
data2011sel$Labour_status[data2011sel$v35a==3] <- 2
data2011sel$Labour_status[data2011sel$v35a==1] <- 3
data2011sel$Labour_status[data2011sel$v35a==2] <- 4
data2011sel$Labour_status[data2011sel$v35a==4] <- 5
data2011sel$Labour_status[data2011sel$v35a==7 | data2011sel$v35a==8] <- 6
data2011sel$Labour_status[data2011sel$v35a==6] <- 99
data2011sel$Labour_status[is.na(data2011sel$Labour_status)] <- 99 

data2011sel$Labour_status <- factor(data2011sel$Labour_status, labels = Labour_labels, ordered = FALSE) 

##Volunteering
data2011sel$v37[data2011sel$v37==2] <- 0

##Dutch language
data2011sel$v51a <- data2011sel$v51a - 1 
data2011sel$v51b <- data2011sel$v51b - 1
data2011sel$v51c <- data2011sel$v51c - 1

##Health
data2011sel$v53 <- 5 - data2011sel$v53

##Education
data2011sel$Educ_interval <- data2011sel$v62a
data2011sel$Educ_interval[data2011sel$v62a==14 | data2011sel$v62a==13] <- NA 
data2011sel$Educ_interval <- recode(data2011sel$Educ_interval,"1=0;2=1;3=2;4:5=3;9:10=4;6:8=5;11=6;12=7")

data2011sel$Educ_ordinal <- recode(data2011sel$Educ_interval,"0:1=0;2:3=1;4:5=2;6:7=3;NA=99")
data2011sel$Educ_ordinal <- factor(data2011sel$Educ_ordinal, labels = Educ_labels, ordered = FALSE)

## Neighbourhood:Wijk71 

data2011sel$Wijk71 <- data2011sel$gebcode
data2011sel$Wijk71 <- recode(data2011sel$gebcode, "2=3001;18=3003;26=3004;32=3011;42=3005;52=3006;189=1009;289=1010")

#variable names recoding
data2011sel <- data2011sel %>% rename(Age = v1, Male = v2, Household = v3a, Ethnicity = st_etni, Tenure = v10, Neigh_responsibility = v18, Neigh_involve = v19a_1R, Contact_neighbours = v42c, Contact_othernei = v42d, Neigh_familiarity = v22a, Neigh_joy_int = v22b, Neigh_cosy = v22c, Neigh_feelhome = v22d, Neigh_notnice = v22e, Neigh_move=v22f, Neigh_lucky=v22g,Neigh_treat=v22h,Neigh_attitudes=v22i,Neigh_youngold=v22j,Neigh_problemsother=v22k,Neigh_problem = v22l, Municipality_support = v27b, Neigh_attachment=v28a,Volunteering = v37, Dutch_read = v51a, Dutch_speak = v51b, Dutch_write = v51c, Health = v53)

##original variables that need to be dropped 

data2011seldef <- subset(data2011sel, select = -c(gebcode,v62a,v34,v35a,v19a_1,v19a_2,v19a_3,v19a_1count,v19a_2count,v19a_3count))

### adding contextual variables.

## missing values:4[Perc_benefits]
# replaced by 4[Perc_benefits(2013)]

Context2011 <- read.csv("C:/Data Mattheus 2.0/Buurtdata context 2011 - Adj.csv", sep = ";")
data2011seldef <- inner_join(data2011seldef, Context2011)




```

Data preparation 2013

``` {r setup, include = FALSE}

##Adress_years => BRP!

##load raw data 2013
data2013 <- read.spss("C:/Data Mattheus 2.0/WO respons 2014 def (2013) edit.sav", use.value.labels = FALSE, to.data.frame = TRUE)

##select relevant variables
data2013sel <- data2013 %>% select(v1, v2, v3a, st_etni, v8, v18, v19a_1, v19a_2, v19a_3, v52c, v52d, v26a, v26b, v26c, v26i, v22b, v22c, v22d, v26d, v26e, v27a, v26f, v22e, v39b, v40a, v43, v44a, v47, v73a, v73b, v73c, v61, v71a, gebcode, GEWICHT_STAD, WAVEID, WAVE)

##Gender
data2013sel$v2[data2013sel$v2==2] <- 0
data2013sel$v2 <- factor(data2013sel$v2, labels = v2_labels, ordered = FALSE)

##Household
data2013sel$v3a <- recode(data2013sel$v3a, "5:12 = 5")
data2013sel$v3a <- factor(data2013sel$v3a, labels = v3a_labels, ordered = FALSE)

##Ethnicity
data2013sel$st_etni <- recode(data2013sel$st_etni, "7=1;4=2;5=3;2=4;1=5;3=6;6=7;12=7")
data2013sel$st_etni <- factor(data2013sel$st_etni, labels = etni_labels, ordered = FALSE)

##Tenure
data2013sel$v8 <-recode(data2013sel$v8, "3=99;2=0;NA=99")
data2013sel$v8 <- factor(data2013sel$v8, labels = v9_labels, ordered = FALSE)

##Neigh_responsibility
data2013sel$v18[is.na(data2013sel$v18)]<- 4
data2013sel$v18 <- factor(data2013sel$v18, labels = v13_labels, ordered = FALSE)

##Neighb_involve
data2013sel$v19a_1R <- recode(data2013sel$v19a_1, "5=0; 1:3=1")
data2013sel$v19a_1R <- factor(data2013sel$v19a_1R, labels = v14a_1_labels, ordered = FALSE)

#countvariable Neighb_involvement
data2013sel$v19a_1count <- recode(data2013sel$v19a_1, "5=0; 1:4=1")
data2013sel$v19a_2count <- recode(data2013sel$v19a_2, "1:3=1; NA=0")
data2013sel$v19a_3count <- recode(data2013sel$v19a_3, "1:3=1; NA=0")

data2013sel$Count_involve <- data2013sel$v19a_1count + data2013sel$v19a_2count + data2013sel$v19a_3count

##Contact_neighbours
data2013sel$v52c <- recode(data2013sel$v52c, "1:2=2")
data2013sel$v52c <- 6 - data2013sel$v52c

##Contact_othernei
data2013sel$v52d <- recode(data2013sel$v52d, "1:2=2")
data2013sel$v52d <- 6 - data2013sel$v52d

## coding positive responses neighbourhood cohesion
#Neigh_familiarity (0=helemaal mee eens ... 4=helemaal mee oneens)
data2013sel$v26a[data2013sel$v26a==6] <- NA
data2013sel$v26a <- data2013sel$v26a - 1

#Neigh_joy_int (0=helemaal mee oneens ... 4=helemaal mee eens)
data2013sel$v26b[data2013sel$v26b==6] <- NA
data2013sel$v26b <- 5 - data2013sel$v26b

#Neigh_cosy
data2013sel$v26c[data2013sel$v26c==6] <- NA
data2013sel$v26c <- 5 - data2013sel$v26c

#Neigh_feelhome
data2013sel$v26i[data2013sel$v26i==6] <- NA
data2013sel$v26i <- 5 - data2013sel$v26i

#Neigh_notnice
data2013sel$v22b[data2013sel$v22b==6] <- NA
data2013sel$v22b <- data2013sel$v22b - 1

#Neigh_move
data2013sel$v22c[data2013sel$v22c==6] <- NA
data2013sel$v22c <- data2013sel$v22c - 1

#Neigh_lucky
data2013sel$v22d[data2013sel$v22d==6] <- NA
data2013sel$v22d <- 5 - data2013sel$v22d

#Neigh_treat
data2013sel$v26d[data2013sel$v26d==6] <- NA
data2013sel$v26d <- data2013sel$v26d - 1

#Neigh_attitudes
data2013sel$v26e[data2013sel$v26e==6] <- NA
data2013sel$v26e <- 5 - data2013sel$v26e

#Neigh_youngold
data2013sel$v27a[data2013sel$v27a==6] <- NA
data2013sel$v27a <- 5 - data2013sel$v27a

#Neigh_problemsother
data2013sel$v26f[data2013sel$v26f==6] <- NA
data2013sel$v26f <- data2013sel$v26f - 1

#Neigh_problem
data2013sel$v22e[data2013sel$v22e==6] <- NA
data2013sel$v22e <- data2013sel$v22e - 1

##Municipality_support
data2013sel$v39b <- factor(data2013sel$v39b, labels = v23b_labels, ordered = FALSE)

##Neigh_attachment
data2013sel$v40a[data2013sel$v40a==6] <- NA
data2013sel$v40a <- 5 - data2013sel$v40a

##Labour_status
data2013sel$Labour_status[data2013sel$v43==2] <- 1
data2013sel$Labour_status[data2013sel$v44a==3| data2013sel$v44a==2| data2013sel$v44a==4] <- 2
data2013sel$Labour_status[data2013sel$v44a==6] <- 3
data2013sel$Labour_status[data2013sel$v44a==5] <- 4
data2013sel$Labour_status[data2013sel$v44a==1] <- 5
data2013sel$Labour_status[data2013sel$v44a==11 | data2013sel$v44a==12] <- 6
data2013sel$Labour_status[data2013sel$v44a==8] <- 99
data2013sel$Labour_status[is.na(data2013sel$Labour_status)] <- 99 

data2013sel$Labour_status <- factor(data2013sel$Labour_status, labels = Labour_labels, ordered = FALSE) 

##Volunteering
data2013sel$v47[data2013sel$v47==2] <- 0

##Dutch language
data2013sel$v73a <- data2013sel$v73a - 1 
data2013sel$v73b <- data2013sel$v73b - 1
data2013sel$v73c <- data2013sel$v73c - 1

##Health
data2013sel$v61 <- 5 - data2013sel$v61

##Education
data2013sel$Educ_interval <- data2013sel$v71a
data2013sel$Educ_interval[data2013sel$Educ_interval==12]<- NA 
data2013sel$Educ_interval <- recode(data2013sel$Educ_interval,"1=0;2=1;3=2;4=3;6=3;5=4;7:8=5;9=6;10=7")

data2013sel$Educ_ordinal <- recode(data2013sel$Educ_interval,"0:1=0;2:3=1;4:5=2;6:7=3;NA=99")
data2013sel$Educ_ordinal <- factor(data2013sel$Educ_ordinal, labels = Educ_labels, ordered = FALSE)

## Neighbourhood:Wijk71 

data2013sel$Wijk71 <- data2013sel$gebcode
data2013sel$Wijk71 <- recode(data2013sel$gebcode, "2=3001;18=3003;26=3004;32=3011;42=3005;52=3006;189=1009;289=1010")

## Adress_years
Woon2013 <- read.csv("C:/Data Mattheus 2.0/Woonduur 2013 WAVEID.csv", sep = ";")
data2013sel <- inner_join(data2013sel, Woon2013)
data2013sel$Adress_years <- data2013sel$Aantal_maanden_op_adres / 12
data2013sel$Adress_years <- round(data2013sel$Adress_years, digits = 4)

#variable names recoding
data2013sel <- data2013sel %>% rename(Age = v1, Male = v2, Household = v3a, Ethnicity = st_etni, Tenure = v8, Neigh_responsibility = v18, Neigh_involve = v19a_1R, Contact_neighbours = v52c, Contact_othernei = v52d, Neigh_familiarity = v26a, Neigh_joy_int = v26b, Neigh_cosy = v26c, Neigh_feelhome = v26i, Neigh_notnice = v22b, Neigh_move=v22c, Neigh_lucky=v22d,  Neigh_treat=v26d, Neigh_attitudes=v26e, Neigh_youngold=v27a, Neigh_problemsother=v26f, Neigh_problem = v22e, Municipality_support = v39b, Neigh_attachment=v40a,Volunteering = v47, Dutch_read = v73a, Dutch_speak = v73b, Dutch_write = v73c, Health = v61)

##original variables that need to be dropped 

data2013seldef <- subset(data2013sel, select = -c(gebcode,v71a,v43,v44a,v19a_1,v19a_2,v19a_3,v19a_1count,v19a_2count,v19a_3count,unieknummer,Aantal_maanden_op_adres))

### adding contextual variables.

Context2013 <- read.csv("C:/Data Mattheus 2.0/Buurtdata context 2013.csv", sep = ";")
data2013seldef <- inner_join(data2013seldef, Context2013)
```

Data preparation 2015

``` {r setup, include = FALSE}

##Adress_years => BRP!!
## not present: Neigh_joy_int

##load raw data 2015
data2015 <- read.spss("C:/Data Mattheus 2.0/Sociale Index enquete 2016 nieuwe versie edit.sav", use.value.labels = FALSE, to.data.frame = TRUE)

##select relevant variables
data2015sel <- data2015 %>% select(v1, v2, v3a, etniciteit_str, VN39, v18, v19_1, v19_2, v19_3,v19_4,v19_5, v52c,v52d, v26a, v26c, v26i, v22b, v22c, v22d, v26d, v26e, v27a, v26f, v22e, v39b, v40a, v43, v44a, v47, v73a, v73b, v73c, v61, v71a, Wijkprofielindeling, GEWICHT_STAD, WAVEID, WAVE)

##Gender
data2015sel$v2[data2015sel$v2==2] <- 0
data2015sel$v2 <- factor(data2015sel$v2, labels = v2_labels, ordered = FALSE)

##Household
data2015sel$v3a <- factor(data2015sel$v3a, labels = v3a_labels, ordered = FALSE)

##Ethnicity
data2015sel$etniciteit_str <- recode(as.numeric(data2015sel$etniciteit_str), "1=6;2=3;3=4;4=1;5=7;6=7;7=7;8=5;9=2")
data2015sel$etniciteit_str <- factor(data2015sel$etniciteit_str, labels = etni_labels, ordered = FALSE)

##Tenure
data2015sel$VN39 <-recode(data2015sel$VN39, "1:7=0;9=1;NA=99")
data2015sel$VN39 <- factor(data2015sel$VN39, labels = v9_labels, ordered = FALSE)

##Neigh_responsibility
data2015sel$v18[is.na(data2015sel$v18)]<- 4
data2015sel$v18 <- factor(data2015sel$v18, labels = v13_labels, ordered = FALSE)

##Neighb_involve
data2015sel$v19R <- recode(data2015sel$v19_5, "1=0;0=1")
data2015sel$v19R <- factor(data2015sel$v19R, labels = v14a_1_labels, ordered = FALSE)

#countvariable Neighb_involvement
data2015sel$v19_2count <- 0
data2015sel$v19_2count[data2015sel$v19_1==1 & data2015sel$v19_2==1] <- 1 
data2015sel$v19_2count[data2015sel$v19_1==1 & data2015sel$v19_3==1] <- 1
data2015sel$v19_2count[data2015sel$v19_1==1 & data2015sel$v19_4==1] <- 1
data2015sel$v19_2count[data2015sel$v19_2==1 & data2015sel$v19_3==1] <- 1
data2015sel$v19_2count[data2015sel$v19_2==1 & data2015sel$v19_4==1] <- 1
data2015sel$v19_2count[data2015sel$v19_3==1 & data2015sel$v19_4==1] <- 1

data2015sel$v19_3count <- 0
data2015sel$v19_3count[data2015sel$v19_1==1 & data2015sel$v19_2==1 & data2015sel$v19_3==1] <- 1
data2015sel$v19_3count[data2015sel$v19_1==1 & data2015sel$v19_3==1 & data2015sel$v19_4==1] <- 1
data2015sel$v19_3count[data2015sel$v19_1==1 & data2015sel$v19_2==1 & data2015sel$v19_4==1] <- 1
data2015sel$v19_3count[data2015sel$v19_2==1 & data2015sel$v19_3==1 & data2015sel$v19_4==1] <- 1

data2015sel$Count_involve <- as.numeric(data2015sel$v19R) + data2015sel$v19_2count + data2015sel$v19_3count

##Contact_neighbours
data2015sel$v52c <- recode(data2015sel$v52c, "1:2=2")
data2015sel$v52c <- 6 - data2015sel$v52c

##Contact_othernei
data2015sel$v52d <- recode(data2015sel$v52d, "1:2=2")
data2015sel$v52d <- 6 - data2015sel$v52d

## coding positive responses neighbourhood cohesion
#Neigh_familiarity (0=helemaal mee eens ... 4=helemaal mee oneens)
data2015sel$v26a[data2015sel$v26a==6] <- NA
data2015sel$v26a <- data2015sel$v26a - 1

#Neigh_cosy
data2015sel$v26c[data2015sel$v26c==6] <- NA
data2015sel$v26c <- 5 - data2015sel$v26c

#Neigh_feelhome
data2015sel$v26i[data2015sel$v26i==6|data2015sel$v26i==43] <- NA
data2015sel$v26i <- 5 - data2015sel$v26i

#Neigh_notnice
data2015sel$v22b[data2015sel$v22b==6] <- NA
data2015sel$v22b <- data2015sel$v22b - 1

#Neigh_move
data2015sel$v22c[data2015sel$v22c==6] <- NA
data2015sel$v22c <- data2015sel$v22c - 1

#Neigh_lucky
data2015sel$v22d[data2015sel$v22d==6] <- NA
data2015sel$v22d <- 5 - data2015sel$v22d

#Neigh_treat
data2015sel$v26d[data2015sel$v26d==6] <- NA
data2015sel$v26d <- data2015sel$v26d - 1

#Neigh_attitudes
data2015sel$v26e[data2015sel$v26e==6] <- NA
data2015sel$v26e <- 5 - data2015sel$v26e

#Neigh_youngold
data2015sel$v27a[data2015sel$v27a==6] <- NA
data2015sel$v27a <- 5 - data2015sel$v27a

#Neigh_problemsother
data2015sel$v26f[data2015sel$v26f==6] <- NA
data2015sel$v26f <- data2015sel$v26f - 1

#Neigh_problem
data2015sel$v22e[data2015sel$v22e==6] <- NA
data2015sel$v22e <- data2015sel$v22e - 1

##Municipality_support
data2015sel$v39b <- factor(data2015sel$v39b, labels = v23b_labels, ordered = FALSE)

##Neigh_attachment
data2015sel$v40a[data2015sel$v40a==6] <- NA
data2015sel$v40a <- 5 - data2015sel$v40a

##Labour_status
data2015sel$Labour_status[data2015sel$v43==2] <- 1
data2015sel$Labour_status[data2015sel$v44a==3| data2015sel$v44a==2| data2015sel$v44a==4] <- 2
data2015sel$Labour_status[data2015sel$v44a==6] <- 3
data2015sel$Labour_status[data2015sel$v44a==5] <- 4
data2015sel$Labour_status[data2015sel$v44a==1] <- 5
data2015sel$Labour_status[data2015sel$v44a==7] <- 6
data2015sel$Labour_status[data2015sel$v44a==8] <- 99
data2015sel$Labour_status[is.na(data2015sel$Labour_status)] <- 99 

data2015sel$Labour_status <- factor(data2015sel$Labour_status, labels = Labour_labels, ordered = FALSE) 

##Volunteering
data2015sel$v47[data2015sel$v47==2] <- 0

##Dutch language
data2015sel$v73a <- data2015sel$v73a - 1 
data2015sel$v73b <- data2015sel$v73b - 1
data2015sel$v73c <- data2015sel$v73c - 1

##Health
data2015sel$v61 <- 5 - data2015sel$v61

##Education
data2015sel$Educ_interval <- data2015sel$v71a
data2015sel$Educ_interval[data2015sel$Educ_interval==12|data2015sel$Educ_interval==11]<- NA 
data2015sel$Educ_interval <- recode(data2015sel$Educ_interval,"1=0;2=1;3=2;4=3;6=3;5=4;7:8=5;9=6;10=7")

data2015sel$Educ_ordinal <- recode(data2015sel$Educ_interval,"0:1=0;2:3=1;4:5=2;6:7=3;NA=99")
data2015sel$Educ_ordinal <- factor(data2015sel$Educ_ordinal, labels = Educ_labels, ordered = FALSE)

## Neighbourhood:Wijk71 
data2015sel <- data2015sel %>% separate(Wijkprofielindeling,c("Wijk71","Name"), sep = ". ")
data2015sel$Wijk71 <- recode(data2015sel$Wijk71, "01=1;04=4")

## Adress_years
Woon2015 <- read.csv("C:/Data Mattheus 2.0/Woonduur 2015 WAVEID.csv", sep = ";")
data2015sel <- inner_join(data2015sel, Woon2015)
data2015sel$Adress_years <- as.numeric(data2015sel$Aantal_maanden_op_adres) / 12
data2015sel$Adress_years <- round(data2015sel$Adress_years, digits = 4)


#variable names recoding
data2015sel <- data2015sel %>% rename(Age = v1, Male = v2, Household = v3a, Ethnicity = etniciteit_str, Tenure = VN39, Neigh_responsibility = v18, Neigh_involve = v19R, Contact_neighbours = v52c, Contact_othernei = v52d, Neigh_familiarity = v26a, Neigh_cosy = v26c, Neigh_feelhome = v26i, Neigh_notnice = v22b, Neigh_move=v22c, Neigh_lucky=v22d,  Neigh_treat=v26d, Neigh_attitudes=v26e, Neigh_youngold=v27a, Neigh_problemsother=v26f, Neigh_problem = v22e, Municipality_support = v39b, Neigh_attachment=v40a,Volunteering = v47, Dutch_read = v73a, Dutch_speak = v73b, Dutch_write = v73c, Health = v61)

##original variables that need to be dropped 
data2015seldef <- subset(data2015sel, select = -c(v71a,v43,v44a,v19_1,v19_2,v19_3,v19_4,v19_5,v19_2count,v19_3count,Name, Codeuniektxt,Aantal_maanden_op_adres))

### adding contextual variables.

Context2015 <- read.csv("C:/Data Mattheus 2.0/Buurtdata context 2015.csv", sep = ";")
data2015seldef <- inner_join(data2015seldef, Context2015)

```

Join all waves 2008,2009,2010,2011,2013,2015
+ Analysis

``` {r setup, include = FALSE}

### Join wave by wave

Full_20082009 <- full_join(data2008seldef, data2009seldef)
Full_20082010 <- full_join(Full_20082009, data2010seldef)
Full_20082011 <- full_join(Full_20082010, data2011seldef)
Full_20082013 <- full_join(Full_20082011, data2013seldef)                                  
Full_20082015 <- full_join(Full_20082013, data2015seldef)

#post-correction
Full_20082015$Labour_status[Full_20082015$WAVE==2015 & Full_20082015$Labour_status=="Volunteer/Other"] <- "Missing"


############ Analysis ######################

## weight data and save scores for Figure 1 (trend figure)

#Neighbourhood involvement
prop.table(table(data2008seldef$Neigh_involve))
wpct(data2008seldef$Neigh_involve, data2008seldef$GEWICHT_STAD)

prop.table(table(data2009seldef$Neigh_involve))
wpct(data2009seldef$Neigh_involve, data2009seldef$GEWICHT_STAD)

prop.table(table(data2010seldef$Neigh_involve))
wpct(data2010seldef$Neigh_involve, data2010seldef$GEWICHT_STAD)

prop.table(table(data2011seldef$Neigh_involve))
wpct(data2011seldef$Neigh_involve, data2011seldef$GEWICHT_STAD)

prop.table(table(data2013seldef$Neigh_involve))
wpct(data2013seldef$Neigh_involve, data2013seldef$GEWICHT_STAD)

prop.table(table(data2015seldef$Neigh_involve))
wpct(data2015seldef$Neigh_involve, data2015seldef$GEWICHT_STAD)

Full_20082015$Perc_N_inv <- NA
Full_20082015$Perc_N_inv[Full_20082015$WAVE==2008] <- 0.2357796
Full_20082015$Perc_N_inv[Full_20082015$WAVE==2009] <- 0.2326045
Full_20082015$Perc_N_inv[Full_20082015$WAVE==2010] <- 0.2304046
Full_20082015$Perc_N_inv[Full_20082015$WAVE==2011] <- 0.2337748 
Full_20082015$Perc_N_inv[Full_20082015$WAVE==2013] <- 0.2339587
Full_20082015$Perc_N_inv[Full_20082015$WAVE==2015] <- 0.2749579

Full_20082015$Perc_N_inv_w <- NA
Full_20082015$Perc_N_inv_w[Full_20082015$WAVE==2008] <- 0.2266144
Full_20082015$Perc_N_inv_w[Full_20082015$WAVE==2009] <- 0.2262049
Full_20082015$Perc_N_inv_w[Full_20082015$WAVE==2010] <- 0.2183327
Full_20082015$Perc_N_inv_w[Full_20082015$WAVE==2011] <- 0.2194426 
Full_20082015$Perc_N_inv_w[Full_20082015$WAVE==2013] <- 0.2164532
Full_20082015$Perc_N_inv_w[Full_20082015$WAVE==2015] <- 0.2550027

#Volunteering
prop.table(table(data2008seldef$Volunteering))
wpct(data2008seldef$Volunteering, data2008seldef$GEWICHT_STAD)

prop.table(table(data2009seldef$Volunteering))
wpct(data2009seldef$Volunteering, data2009seldef$GEWICHT_STAD)

prop.table(table(data2010seldef$Volunteering))
wpct(data2010seldef$Volunteering, data2010seldef$GEWICHT_STAD)

prop.table(table(data2011seldef$Volunteering))
wpct(data2011seldef$Volunteering, data2011seldef$GEWICHT_STAD)

prop.table(table(data2013seldef$Volunteering))
wpct(data2013seldef$Volunteering, data2013seldef$GEWICHT_STAD)

prop.table(table(data2015seldef$Volunteering))
wpct(data2015seldef$Volunteering, data2015seldef$GEWICHT_STAD)

Full_20082015$Perc_Volunteer <- NA
Full_20082015$Perc_Volunteer[Full_20082015$WAVE==2008] <- 0.2304545 
Full_20082015$Perc_Volunteer[Full_20082015$WAVE==2009] <- 0.2379408
Full_20082015$Perc_Volunteer[Full_20082015$WAVE==2010] <- 0.2326607
Full_20082015$Perc_Volunteer[Full_20082015$WAVE==2011] <- 0.2178457 
Full_20082015$Perc_Volunteer[Full_20082015$WAVE==2013] <- 0.2213054
Full_20082015$Perc_Volunteer[Full_20082015$WAVE==2015] <- 0.2462245

Full_20082015$Perc_Volunteer_w <- NA
Full_20082015$Perc_Volunteer_w[Full_20082015$WAVE==2008] <- 0.219716 
Full_20082015$Perc_Volunteer_w[Full_20082015$WAVE==2009] <- 0.2279223
Full_20082015$Perc_Volunteer_w[Full_20082015$WAVE==2010] <- 0.2266389
Full_20082015$Perc_Volunteer_w[Full_20082015$WAVE==2011] <- 0.2118029 
Full_20082015$Perc_Volunteer_w[Full_20082015$WAVE==2013] <- 0.2132327
Full_20082015$Perc_Volunteer_w[Full_20082015$WAVE==2015] <- 0.2346285

## Chi-square tests (with/without 2015)

Chitest_N_inv <- table(Full_20082013$WAVE, Full_20082013$Neigh_involve)
chisq.test(Chitest_N_inv)

Chitest_Volunteer <- table(Full_20082013$WAVE, Full_20082013$Volunteering)
chisq.test(Chitest_Volunteer)


Chitest_N_inv1 <- table(Full_20082015$WAVE, Full_20082015$Neigh_involve)
chisq.test(Chitest_N_inv1)

Chitest_Volunteer1 <- table(Full_20082015$WAVE, Full_20082015$Volunteering)
chisq.test(Chitest_Volunteer1)

### plotting trend in neighbourhood involvement and volunteering

## weighted plot

#Fig1_w <- ggplot(Full_20082015, aes(x=factor(WAVE))) + geom_line(aes(y=Perc_N_inv_w,group=1,color="Neighbourhood involvement")) + geom_line(aes(y=Perc_Volunteer_w, group=1,color="Volunteering")) + geom_point(aes(y=Perc_N_inv_w,color="Neighbourhood involvement")) +geom_point(aes(y=Perc_Volunteer_w,color="Volunteering"))  + expand_limits(y=c(0.15,0.3))


#Full_20082015.long <- melt(Full_20082015, id = "WAVE", measure = c("Perc_N_inv_w","Perc_Volunteer_w"))
#Fig1_w2 <- ggplot(Full_20082015.long, aes(WAVE, value, colour=variable, shape=variable))
#Fig1_w2 + geom_line() + expand_limits(y=c(0.15,0.3)) + geom_point()

## unweighted plot

Full_20082015.long2 <- melt(Full_20082015, id = "WAVE", measure = c("Perc_N_inv","Perc_Volunteer"))
Fig1 <- ggplot(Full_20082015.long2, aes(WAVE, value, group=variable))
Fig1 + geom_line(aes(linetype=variable), position=position_dodge(0.15)) + expand_limits(y=c(0.175,0.325)) + geom_point(aes(shape=variable),position=position_dodge(0.15), size=2.5) + scale_x_continuous(breaks = c(2008,2009,2010,2011,2012,2013,2014,2015)) + xlab("Year of survey") + ylab("% Civic participation")+ theme_bw() + labs(shape="Civic participation", linetype="Civic participation") + scale_shape_discrete(labels = c("Neighbourhood involvement","Volunteering"))+  scale_linetype_discrete(labels = c("Neighbourhood involvement","Volunteering"))

## factor analysis neighbourhood SES + save scores

fa <- factanal(~Low_40+Disposable_income+Perc_unemployed+Perc_benefits, factors = 1, data = Full_20082015, scores = "regression")

fa

Full_20082015 <- cbind(Full_20082015, fa$scores)
Full_20082015$Neigh_SES <- 0 - Full_20082015$Factor1

describe(Full_20082015$Neigh_SES)

# Test Factor
d <- data.frame(Low40=Full_20082015$Low_40, Disp=Full_20082015$Disposable_income,Unemp=Full_20082015$Perc_unemployed,Benef=Full_20082015$Perc_benefits, factor=Full_20082015$Neigh_SES)
cor(d)

#Cronbach's alpha
library(psych)

d1 <- data.frame(Low40=Full_20082015$Low_40, Disp=Full_20082015$Disposable_income,Unemp=Full_20082015$Perc_unemployed,Benef=Full_20082015$Perc_benefits)
alpha(d1, keys = c("Disp"))

d2 <- data.frame(read=Full_20082015$Dutch_read,speak=Full_20082015$Dutch_speak,write=Full_20082015$Dutch_write)
alpha(d2)

library(Hmisc)

Full_20082015$Dutch_prof <- (Full_20082015$Dutch_read + Full_20082015$Dutch_speak+Full_20082015$Dutch_write)/3
describe(Full_20082015$Dutch_prof)

```

Regression analyses

``` {r setup, include = FALSE}

##List variables to be used: Age, Male, Household, Ethnicity, Tenure, (Adress_years), Labour_status, Dutch_prof, Health, Educ_ordinal, Wijk71,	Neigh_SES,	Herf_div, Turnover

## remove NA both Neigh_involve and Volunteering. 1123 respondents excluded (out of 80065) => 78942
#Dataset with all removed (78433)
Full_20082015A <- drop_na(Full_20082015, Neigh_involve, Volunteering,Age, Male, Household, Ethnicity, Tenure, Educ_ordinal, Labour_status, Health, Dutch_prof)

# create Neighbourhood-Year unique value. number of unique values: 422

Full_20082015A$Neigh_year <- Full_20082015A$WAVE/100000 + Full_20082015A$Wijk71/10000
#describe(Full_20082015$Neigh_year)

# rescale Wijk 71 and WAVE

Full_20082015A$Wijk71_sc <- Full_20082015A$Wijk71/10000
#describe(Full_20082015$Wijk71_sc)

Full_20082015A$WAVE_sc <- Full_20082015A$WAVE/10000
#describe(Full_20082015$WAVE_sc)

Full_20082015A <- cbind(Full_20082015A, dummy(Full_20082015A$WAVE, sep = "_"))

## Mean-center contextual variables

Full_20082015A$Herf_div_mean <- Full_20082015A$Herf_div - mean(Full_20082015A$Herf_div, na.rm = TRUE)
Full_20082015A$Turnover_mean <- Full_20082015A$Turnover - mean(Full_20082015A$Turnover, na.rm = TRUE)

## Mean-center Age + create Age-square, Health + Dutch_prof

Full_20082015A$Age_2 <- Full_20082015A$Age^2
Full_20082015A$Age_mean <- Full_20082015A$Age - mean(Full_20082015A$Age, na.rm=TRUE)
Full_20082015A$Age_mean_sc <- Full_20082015A$Age_mean/10
Full_20082015A$Age_2_mean <- Full_20082015A$Age_2 - mean(Full_20082015A$Age_2, na.rm=TRUE)
Full_20082015A$Age_2_mean_sc <- Full_20082015A$Age_2_mean/1000


Full_20082015A$Health_mean <- Full_20082015A$Health - mean(Full_20082015A$Health, na.rm=TRUE)
Full_20082015A$Dutch_prof_mean <- Full_20082015A$Dutch_prof - mean(Full_20082015A$Dutch_prof, na.rm=TRUE)

## with contextuals as dummies

Full_20082015A <- Full_20082015A %>% group_by(WAVE) %>% mutate(Neigh_SES_5= ntile(Neigh_SES, 5))
Full_20082015A <- Full_20082015A %>% group_by(WAVE) %>% mutate(Neigh_SES_10= ntile(Neigh_SES, 10))
Full_20082015A <- Full_20082015A %>% group_by(WAVE) %>% mutate(Herf_div_mean_5= ntile(Herf_div_mean, 5))
Full_20082015A <- Full_20082015A %>% group_by(WAVE) %>% mutate(Turnover_mean_5= ntile(Turnover_mean, 5))

#### construction of three spline coefficients (based on plot Neigh_SES_5, Neigh_involve)

# first spline: small changes 2009-2009
Full_20082015A$Spline1 <- 0
Full_20082015A$Spline1[Full_20082015A$WAVE==2008] <- 1

# second spline: decline/rise 2009-2013
Full_20082015A$Spline2 <- 0
Full_20082015A$Spline2[Full_20082015A$WAVE==2009] <- 1
Full_20082015A$Spline2[Full_20082015A$WAVE==2010] <- 2
Full_20082015A$Spline2[Full_20082015A$WAVE==2011] <- 3
Full_20082015A$Spline2[Full_20082015A$WAVE==2013] <- 4
Full_20082015A$Spline2[Full_20082015A$WAVE==2015] <- 4

# third spline

Full_20082015A$Spline3 <- 0
Full_20082015A$Spline3[Full_20082015A$WAVE==2015] <- 1

##File without WAVE 2015 (nog checken incl missings 2015)

Full_20082015B <- Full_20082015A 
Full_20082015B$WAVE[Full_20082015B$WAVE==2015] <- NA
Full_20082015B <- drop_na(Full_20082015B, WAVE)

Full_20082015B$Spline2a <- 0
Full_20082015B$Spline2a[Full_20082015B$WAVE==2009] <- 0
Full_20082015B$Spline2a[Full_20082015B$WAVE==2010] <- 1
Full_20082015B$Spline2a[Full_20082015B$WAVE==2011] <- 2
Full_20082015B$Spline2a[Full_20082015B$WAVE==2013] <- 3
## deze gebruiken => scores pas hoger dan 0 na verandering!

### Nullmodels, compare fit
# Neigh_involve

#Model0 <- glm(Neigh_involve ~ 1, data = Full_20082015A,family = binomial(link="logit"))
#summary(Model0)

#Model0A <- glmer(Neigh_involve ~ (1|Neigh_SES), data = Full_20082015,family = binomial(link="logit"))
#summary(Model0A)

#Model0B <- glmer(Neigh_involve ~ (1|Wijk71), data = Full_20082015,family = binomial(link="logit"))
#summary(Model0B)

#Model0C <- glmer(Neigh_involve ~ (1|WAVE)+ (1|Neigh_SES) , data = Full_20082015,family = binomial(link="logit"))
#summary(Model0C)

#Model0D <- glmer(Neigh_involve ~ (1|Wijk71)+ (1|Neigh_SES) , data = Full_20082015,family = binomial(link="logit"))
#summary(Model0D)

#Model0E <- glmer(Neigh_involve ~ (1|Wijk71)+ (1|WAVE) , data = Full_20082015,family = binomial(link="logit"))
#summary(Model0E)

#Model0F <- glmer(Neigh_involve ~ (1|Neigh_SES) + (1|Wijk71)+ (1|WAVE) , data = Full_20082015A,family = binomial(link="logit"))
#summary(Model0F)

Model0Fa <- glmer(Neigh_involve ~ (1|Neigh_year) + (1|Wijk71)+ (1|WAVE) , data = Full_20082015A,family = binomial(link="logit"))
summary(Model0Fa)

# model with unique Neighbourhood-year values does not have lower AIC or BIC


### Models with contextual variables

Model1 <- glmer(Neigh_involve ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Neigh_SES + Herf_div_mean+ Turnover_mean, data = Full_20082015A,family = binomial(link="logit"))
summary(Model1)

#correlations contextual variables

#d3 <- data.frame(Full_20082015$Neigh_SES, Full_20082015$Herf_div, Full_20082015$Turnover)
#cor(d3)

### Model with some individual predictors. 

#Model1.5 <- glmer(Neigh_involve ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Neigh_SES + Herf_div_mean+ Turnover_mean + Educ_ordinal + as.factor(WAVE_sc), data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
#summary(Model1.5)

#Model2 <- glmer(Neigh_involve ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Neigh_SES + Herf_div_mean + Turnover_mean + Age_mean_sc + Male + Household+ Ethnicity + Tenure + Educ_ordinal + as.factor(WAVE_sc), data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
#summary(Model2)

#Model2a <- glmer(Neigh_involve ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Neigh_SES + Herf_div_mean + Turnover_mean + Age_mean_sc + Male + Household+ Ethnicity + Tenure + Educ_ordinal + as.factor(WAVE_sc), data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
#summary(Model2a)

#Model3 <- glmer(Neigh_involve ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Neigh_SES + Herf_div_mean + Turnover_mean + Age_mean_sc + Male + Household + Ethnicity + Tenure + Educ_ordinal + as.factor(WAVE_sc) + Labour_status + Health_mean + Dutch_prof_mean, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
#summary(Model3)

Model3NI <- glmer(Neigh_involve ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Labour_status, data = Full_20082015B, family = binomial(link = "logit"), nAGQ = 0)
summary(Model3NI)

Model3V <- glmer(Volunteering ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Labour_status, data = Full_20082015B, family = binomial(link = "logit"), nAGQ = 0)
summary(Model3V)

Full_20082015B$Neigh_involve_num <- as.numeric(Full_20082015B$Neigh_involve) - 1


aggregate(Neigh_involve_num ~ Labour_status, data = Full_20082015B, FUN = mean)
aggregate(Volunteering ~ Labour_status+WAVE, data = Full_20082015B, FUN = mean)


#mcDiagnose(Model3)

#Model3a <- glmer(Neigh_involve ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Neigh_SES + Turnover_mean + Age_mean_sc + Male + Household + Ethnicity + Tenure + Educ_ordinal + as.factor(WAVE_sc) + Labour_status + Health_mean + Dutch_prof_mean, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
#summary(Model3a)

#Model3b <- glmer(Neigh_involve ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Herf_div_mean + Turnover_mean + Age_mean_sc + Male + Household + Ethnicity + Tenure + Educ_ordinal + as.factor(WAVE_sc) + Labour_status + Health_mean + Dutch_prof_mean, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
#summary(Model3b)

#Model4 <- glmer(Neigh_involve ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Neigh_SES + Herf_div_mean + Turnover_mean + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure + Educ_ordinal + as.factor(WAVE_sc) + Labour_status + Health_mean + Dutch_prof_mean, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
#summary(Model4)

#####no significant better fits with context dummies

#Model5 <- glmer(Neigh_involve ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Neigh_SES + Herf_div_mean + Turnover_mean + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure + Educ_ordinal +  Full_20082015A_2009 + Full_20082015A_2010 + Full_20082015A_2011 +  Full_20082015A_2013 + Full_20082015A_2015  + Labour_status + Health_mean + Dutch_prof_mean + Neigh_SES:Full_20082015A_2013, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
#summary(Model5)

#Model5a <- glmer(Neigh_involve ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Neigh_SES + Herf_div_mean + Turnover_mean + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure + Educ_ordinal +  Full_20082015A_2008 + Full_20082015A_2010 + Full_20082015A_2011 +  Full_20082015A_2013 + Full_20082015A_2015  + Labour_status + Health_mean + Dutch_prof_mean + factor(Neigh_SES_5):Full_20082015A_2013, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
#summary(Model5a)


# Volunteering test

#Model5aV <- glmer(Volunteering ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Neigh_SES + Herf_div_mean + Turnover_mean + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure + Educ_ordinal +  Full_20082015A_2009 + Full_20082015A_2010 + Full_20082015A_2011 +  Full_20082015A_2013 + Full_20082015A_2015  + Labour_status + Health_mean + Dutch_prof_mean + factor(Neigh_SES_5):Full_20082015A_2013, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
#summary(Model5aV)


#### analyses with spline coefficients ####

### Neighbourhoog involvement

#Model1spl <- glmer(Neigh_involve ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Spline1 + Spline2 + Spline3, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
#summary(Model1spl)

N_Model4spl <- glmer(Neigh_involve ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Educ_ordinal +  Labour_status + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure +  Health_mean + Dutch_prof_mean + Neigh_SES + Herf_div_mean + Turnover_mean + Spline1 + Spline2 + Spline3, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
summary(N_Model4spl)

N_Model4splb <- glmer(Neigh_involve ~ (1+Spline2|Neigh_SES) + (1|Wijk71_sc)+ (1|WAVE_sc) + Educ_ordinal +  Labour_status + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure +  Health_mean + Dutch_prof_mean + Neigh_SES + Herf_div_mean + Turnover_mean + Spline1 + Spline2 + Spline3, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
summary(N_Model4splb)

## interaction model
N_Model5spl <- glmer(Neigh_involve ~ (1+ Neigh_SES|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Educ_ordinal +  Labour_status + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure +  Health_mean + Dutch_prof_mean + Neigh_SES + Herf_div_mean + Turnover_mean + Spline1 + Spline2 + Spline3 + Spline2:Neigh_SES, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
summary(N_Model5spl)


N_Model5spla <- glmer(Neigh_involve ~ (1+Spline2|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Educ_ordinal +  Labour_status + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure +  Health_mean + Dutch_prof_mean + Neigh_SES + Herf_div_mean + Turnover_mean + Spline1 + Spline2 + Spline3 + Spline2:Neigh_SES, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
summary(N_Model5spla)

N_Model5splb <- glmer(Neigh_involve ~ (1+Spline2|Neigh_SES) + (1|Wijk71_sc)+ (1|WAVE_sc) + Educ_ordinal +  Labour_status + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure +  Health_mean + Dutch_prof_mean + Neigh_SES + Herf_div_mean + Turnover_mean + Spline1 + Spline2 + Spline3 + Spline2:Neigh_SES, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
summary(N_Model5splb)

### Volunteering

V_Model4spl <- glmer(Volunteering ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Educ_ordinal +  Labour_status + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure +  Health_mean + Dutch_prof_mean + Neigh_SES + Herf_div_mean + Turnover_mean + Spline1 + Spline2 + Spline3, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
summary(V_Model4spl)

v9_labels

## interaction model
V_Model5spl <- glmer(Volunteering ~ (1+ Neigh_SES|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Educ_ordinal +  Labour_status + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure +  Health_mean + Dutch_prof_mean + Neigh_SES + Herf_div_mean + Turnover_mean + Spline1 + Spline2 + Spline3 + Spline2:Neigh_SES, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
summary(V_Model5spl)

# test -Age^2
V_Model5spltest <- glmer(Volunteering ~ (1+ Neigh_SES|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Neigh_SES + Herf_div_mean + Turnover_mean + Age_mean_sc + Male + Household + Ethnicity + Tenure + Educ_ordinal +  Labour_status + Health_mean + Dutch_prof_mean + Spline1 + Spline2 + Spline3 + Spline2:Neigh_SES, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
summary(V_Model5spltest)

table(Full_20082015A$Tenure, exclude = NULL)

# take volunteers out of data-set (temp)
table(Full_20082015A$Labour_status)

Full_20082015B <- Full_20082015A
Full_20082015B$Labour_status[Full_20082015B$Labour_status == "Volunteer/Other" ] <- NA

N_Model5testA <- glmer(Neigh_involve ~ (1+Spline2|Neigh_SES) + (1|Wijk71_sc)+ (1|WAVE_sc) + Educ_ordinal +  Labour_status + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure +  Health_mean + Dutch_prof_mean + Neigh_SES + Herf_div_mean + Turnover_mean + Spline1 + Spline2 + Spline3 + Spline2:Neigh_SES, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
summary(N_Model5testA)

N_Model5testB <- glmer(Neigh_involve ~ (1+Spline2|Neigh_SES) + (1|Wijk71_sc)+ (1|WAVE_sc) + Educ_ordinal +  Labour_status + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure +  Health_mean + Dutch_prof_mean + Neigh_SES + Herf_div_mean + Turnover_mean + Spline1 + Spline2 + Spline3 + Spline2:Neigh_SES, data = Full_20082015B,family = binomial(link="logit"), nAGQ = 0)
summary(N_Model5testB)

### almost no differences in outcomes between nAGQ = 0 or nAGQ = 1.

## tests without 2015

N_M5 <- glmer(Neigh_involve ~ (1+Spline2|Neigh_SES) + (1|Wijk71_sc)+ (1|WAVE_sc) + Educ_ordinal +  Labour_status + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure +  Health_mean + Dutch_prof_mean + Neigh_SES + Herf_div_mean + Turnover_mean + Spline1 + Spline2 + Spline2:Neigh_SES, data = Full_20082015B,family = binomial(link="logit"), nAGQ = 0)
summary(N_M5)

N_M5a <- glmer(Neigh_involve ~ (1+Spline2a|Neigh_SES) + (1|Wijk71_sc)+ (1|WAVE_sc) + Educ_ordinal +  Labour_status + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure +  Health_mean + Dutch_prof_mean + Neigh_SES + Herf_div_mean + Turnover_mean + Spline1 + Spline2a + Spline2a:Neigh_SES, data = Full_20082015B,family = binomial(link="logit"), nAGQ = 0)
summary(N_M5a)

Full_20082015B$predictN_M5a <- predict(N_M5a, type = "response", newdata = NULL)

Predictplot <- ggplot(Full_20082015B, aes(x=factor(Spline2a), y=predictN_M5a, group=Neigh_SES_5, linetype = factor(Neigh_SES_5)))

Predictplot + stat_summary(fun.y=mean, geom="line")+ stat_summary(fun.data = mean_cl_normal, geom = "linerange")+ expand_limits(y=c(0.15,0.35))

V_M5 <- glmer(Volunteering ~ (1+Spline2|Neigh_SES) + (1|Wijk71_sc)+ (1|WAVE_sc) + Educ_ordinal +  Labour_status + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure +  Health_mean + Dutch_prof_mean + Neigh_SES + Herf_div_mean + Turnover_mean + Spline1 + Spline2 + Spline2:Neigh_SES, data = Full_20082015B,family = binomial(link="logit"), nAGQ = 0)
summary(V_M5)

V_M5a <- glmer(Volunteering ~ (1+Spline2a|Neigh_SES) + (1|Wijk71_sc)+ (1|WAVE_sc) + Educ_ordinal +  Labour_status + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure +  Health_mean + Dutch_prof_mean + Neigh_SES + Herf_div_mean + Turnover_mean + Spline1 + Spline2a + Spline2a:Neigh_SES, data = Full_20082015B,family = binomial(link="logit"), nAGQ = 0)
summary(V_M5a)

Full_20082015B$predictV_M5a <- predict(V_M5a, type = "response", newdata = NULL)

Predictplot2 <- ggplot(Full_20082015B, aes(x=factor(Spline2a), y=predictV_M5a, group=Neigh_SES_5, linetype = factor(Neigh_SES_5)))

Predictplot2 + stat_summary(fun.y=mean, geom="line") + stat_summary(fun.data = mean_cl_normal, geom = "linerange") + expand_limits(y=c(0.15,0.35))

plot_age2 <- ggplot(Full_20082015B, aes(x=Age, y=predictV_M5a))
plot_age2 + stat_summary(fun.y=mean, geom="line") + stat_summary(fun.data = mean_cl_normal, geom = "linerange")

plot_age2a <- ggplot(Full_20082015B, aes(x=Age, y=Volunteering))
plot_age2a + stat_summary(fun.y=mean, geom="line")

?stat_summary

## further testing model Model5splA by omitting variables
#omit + Dutch_prof_mean
#Model5splA1 <- glmer(Neigh_involve ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Neigh_SES + Herf_div_mean + Turnover_mean + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure + Educ_ordinal + Spline1 + Spline2 + Spline3  + Labour_status + Health_mean +  Neigh_SES:Spline2, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
#summary(Model5splA1)

# + Labour status
#Model5splA2 <- glmer(Neigh_involve ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Neigh_SES + Herf_div_mean + Turnover_mean + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure + Educ_ordinal + Spline1 + Spline2 + Spline3 + Health_mean +  Neigh_SES:Spline2, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
#summary(Model5splA2)

### Volunteering

#Model4splVOL <- glmer(Volunteering ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Neigh_SES + Herf_div_mean + Turnover_mean + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure + Educ_ordinal + Spline1 + Spline2 + Spline3  + Labour_status + Health_mean + Dutch_prof_mean, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
#summary(Model4splVOL)


#Model5splVOL <- glmer(Volunteering ~ (1|Neigh_year) + (1|Wijk71_sc)+ (1|WAVE_sc) + Neigh_SES + Herf_div_mean + Turnover_mean + Age_mean_sc  + Male + Household + Ethnicity + Tenure + Educ_ordinal + Spline1 + Spline2 + Spline3  + Labour_status + Health_mean + Dutch_prof_mean + Neigh_SES:Spline2, data = Full_20082015A,family = binomial(link="logit"), nAGQ = 0)
#summary(Model5splVOL)

#mcDiagnose(Model5splVOL)


#### tests with plotting predicted values

describe(Full_20082015A$Neigh_SES)

Full_20082015A$predictN_Model5testA <- predict(N_Model5testA, type = "response", newdata = NULL)

Predictplot <- ggplot(Full_20082015A, aes(x=factor(Spline2), y=predictN_Model5testA, group=Neigh_SES_5, linetype = factor(Neigh_SES_5)))

Predictplot + stat_summary(fun.y=mean, geom="line") + expand_limits(y=c(0.15,0.35))

Predictplot + geom_line()

?stat_summary

?margins
?predict

Predictplot + stat_smooth(se=FALSE)

predictdata <-  data.frame(Neigh_SES_5 = seq(1,5, length = 5))
predictdata$test <- predict(N_Model5splb, type = "response", newdata = predictdata)

rm(predictdata)

#predictdata2 <- expand.grid(Educ_ordinal=unique(Full_20082015B$Educ_ordinal),Labour_status=unique(Full_20082015B$Labour_status),Age_mean_sc=unique(Full_20082015B$Age_mean_sc),Age_2_mean_sc=unique(Full_20082015B$Age_2_mean_sc),Male=unique(Full_20082015B$Male),Household=unique(Full_20082015B$Household),Ethnicity=unique(Full_20082015B$Ethnicity),Tenure=unique(Full_20082015B$Tenure),Health_mean=unique(Full_20082015B$Health_mean),Dutch_prof_mean=unique(Full_20082015B$Dutch_prof_mean),Dutch_prof_mean=unique(Full_20082015B$Dutch_prof_mean),Neigh_SES=unique(Full_20082015B$Neigh_SES),Herf_div_mean=unique(Full_20082015B$Herf_div_mean),Turnover_mean=unique(Full_20082015B$Turnover_mean),Spline1=unique(Full_20082015B$Spline1),Spline2=unique(Full_20082015B$Spline2),Spline3=unique(Full_20082015B$Spline3))
# te lange vectors met alle combi's                          

View(predictdata2)
                          
                          
Educ_ordinal +  Labour_status + Age_mean_sc + Age_2_mean_sc + Male + Household + Ethnicity + Tenure +  Health_mean + Dutch_prof_mean + Neigh_SES + Herf_div_mean + Turnover_mean + Spline1 + Spline2 + Spline3 + Spline2:Neigh_SES

## maak nieuwe datasets met combinatie uniquevalues. (zie syntax luc) 

    

```

``` {r setup, include = FALSE}

#### plots split by neighbourhood variables

## Neighbourhood involvment

Full_20082015A$Neigh_involve_num <- as.numeric(Full_20082015A$Neigh_involve) - 1

G_neigh <- ggplot(Full_20082015A, aes(x=WAVE, y=Neigh_involve_num, group=Neigh_SES_5, linetype = factor(Neigh_SES_5),shape = factor(Neigh_SES_5))) 
G_neigh + stat_summary(fun.y=mean,position = position_dodge(0.15), geom="line")+ stat_summary(fun.y=mean,position = position_dodge(0.15), geom = "point")+ expand_limits(y=c(0.15,0.35))+ scale_x_continuous(breaks = c(2008,2009,2010,2011,2012,2013,2014,2015))+ labs(x="Year of survey",y="% Neighbourhood involvement",shape="Neighbourhood SES (quintiles)", linetype="Neighbourhood SES (quintiles)") + guides(shape=guide_legend(reverse = TRUE), linetype=guide_legend(reverse = TRUE)) + theme_bw()

#G2 <- ggplot(Full_20082015A, aes(x=WAVE, y=Neigh_involve_num, group=Herf_div_mean_5, linetype = factor(Herf_div_mean_5),shape = factor(Herf_div_mean_5))) 
#G2 + stat_summary(fun.y=mean,position = position_dodge(0.15), geom="line")+ stat_summary(fun.y=mean,position = position_dodge(0.15), geom = "point")+ expand_limits(y=c(0.15,0.35))+ scale_x_continuous(breaks = c(2008,2009,2010,2011,2012,2013,2014,2015))+ labs(x="Year of survey",y="% Neighbourhood involvement",shape="Diversity - Herfindahl (quintiles)", linetype="Diversity - Herfindahl (quintiles)")  + theme_bw()

#G3 <- ggplot(Full_20082015A, aes(x=WAVE, y=Neigh_involve_num, group=Turnover_mean_5, linetype = factor(Turnover_mean_5),shape = factor(Turnover_mean_5))) 
#G3 + stat_summary(fun.y=mean,position = position_dodge(0.15), geom="line")+ stat_summary(fun.y=mean,position = position_dodge(0.15), geom = "point")+ expand_limits(y=c(0.15,0.35))+ scale_x_continuous(breaks = c(2008,2009,2010,2011,2012,2013,2014,2015))+ labs(x="Year of survey",y="% Neighbourhood involvement",shape="Turnover rate (quintiles)", linetype="Turnover rate (quintiles)")  + theme_bw()


## Volunteering

Full_20082015A$Volunteering_num <- as.numeric(Full_20082015A$Volunteering)

G_vol <- ggplot(Full_20082015A, aes(x=WAVE, y=Volunteering_num, group=Neigh_SES_5, linetype = factor(Neigh_SES_5),shape = factor(Neigh_SES_5))) 
G_vol + stat_summary(fun.y=mean,position = position_dodge(0.15), geom="line")+ stat_summary(fun.y=mean,position = position_dodge(0.15), geom = "point")+ expand_limits(y=c(0.15,0.35))+ scale_x_continuous(breaks = c(2008,2009,2010,2011,2012,2013,2014,2015))+ labs(x="Year of survey",y="% Volunteering",shape="Neighbourhood SES (quintiles)", linetype="Neighbourhood SES (quintiles)") + guides(shape=guide_legend(reverse = TRUE), linetype=guide_legend(reverse = TRUE)) + theme_bw()

```

``` {r setup, include = FALSE}

### some tests with summarising and plotting data

## Participation by Neigh SES per wave (influential cases?)

G_out_V <- ggplot(Full_20082015A, aes(x=Neigh_SES,y=Volunteering_num))
G_out_V + stat_summary(fun.y = mean, geom = "point") + facet_wrap(~WAVE) + geom_smooth()

Full_20082015Atest <- Full_20082015A %>% group_by(WAVE, Wijk71) %>% summarise(mean_V = mean(Volunteering_num))

table(Full_20082015A$mean_Volunteering)


??geom


Full_20082015a <- Full_20082015
Full_20082015a$Neigh_involve <- as.numeric(Full_20082015$Neigh_involve) - 1
#table(Full_20082015a$Neigh_involve)
#describe(Full_20082015a$Neigh_involve)

Full_20082015a <- Full_20082015a %>% group_by(WAVE,Wijk71) %>% mutate(Neigh_inv_mean_unw = mean(Neigh_involve, na.rm=TRUE))

describe(Full_20082015a$disp_inc_10)

?sapply

#table(Full_20082015a$Neigh_inv_mean_unw)

describe(Full_20082015a$Neigh_involve)

g <- ggplot(Full_20082015a, aes(x = factor(WAVE), y = Neigh_inv_mean_unw)) 

g1 <- ggplot(Full_20082015a, aes(x = factor(WAVE), y = Neigh_inv_mean_unw, colour= Low_40)) 

g + geom_boxplot()

g1 + geom_point() + facet_wrap(~Wijk71)

Full_20082015a <- Full_20082015a %>% group_by(WAVE) %>% mutate(Neigh_inv_mean_wave = mean(Neigh_involve, na.rm=TRUE))

ga <- ggplot(Full_20082015a, aes(x = factor(WAVE), y = Neigh_inv_mean_wave))

gb <- ggplot(Full_20082015a, aes(x=factor(WAVE), y=Neigh_involve, group=1)) 

ga + geom_point()+ geom_line()

gb + stat_summary(fun.y=mean, geom="line") + expand_limits(y=c(0.2,0.3))

?stat_summary

## neigh disposable income


Full_20082015a <- Full_20082015a %>% group_by(WAVE) %>% mutate(disp_inc_10 = ntile(Disposable_income, 10))

Full_20082015a <- Full_20082015a %>% group_by(WAVE, disp_inc_10) %>% mutate(Neigh_inv_DI10 = mean(Neigh_involve, na.rm=TRUE)) 

Full_20082015a <- Full_20082015a %>% group_by(WAVE) %>% mutate(disp_inc_5 = ntile(Disposable_income, 5))

Full_20082015a <- Full_20082015a %>% group_by(WAVE, disp_inc_5) %>% mutate(Neigh_inv_DI5 = mean(Neigh_involve, na.rm=TRUE)) 
               

g2 <- ggplot(Full_20082015a, aes(x = WAVE, y = Neigh_inv_DI10, colour = factor(disp_inc_10)))

g2 + geom_point() + geom_line()

g3 <- ggplot(Full_20082015a, aes(x = WAVE, y = Neigh_inv_DI5, colour = factor(disp_inc_5)))

g3 + geom_point() + geom_line()

?geom_line


## education groups

Full_20082015a <- Full_20082015a %>% group_by(WAVE,Educ_ordinal) %>% mutate(Neigh_inv_educ = mean(Neigh_involve, na.rm=TRUE))

#table(Full_20082015a$Educ_ordinal, exclude = NULL)

#describe(Full_20082015a$Neigh_inv_educ)

g4 <- ggplot(Full_20082015a, aes(x = WAVE, y = Neigh_inv_educ, colour = Educ_ordinal))

g4+ geom_point() + geom_line()

### labour status

table(Full_20082015a$Labour_status, exclude = NULL)

Full_20082015a <- Full_20082015 %>% group_by(WAVE,Labour_status) %>% mutate(Neigh_inv_LS = mean(Neigh_involve, na.rm=TRUE))

describe(Full_20082015a$Neigh_inv_LS)

g5 <- ggplot(Full_20082015a, aes(x = WAVE, y = Neigh_inv_LS, colour = Labour_status))

g5 + geom_point() + geom_line()

###

describe(Full_20082015$GEWICHT_STAD)

Full_20082015a$Neigh_involve_w <- xtabs(GEWICHT_STAD ~ Neigh_involve, data = Full_20082015a)

wpct(Full_20082015a$Neigh_involve)
wpct(Full_20082015a$Neigh_involve, Full_20082015a$GEWICHT_STAD)

Full_20082015a$Neigh_involve_w <- (Full_20082015a$Neigh_involve*Full_20082015a$GEWICHT_STAD)/Full_20082015a$GEWICHT_STAD

table(Full_20082015a$Neigh_involve)

wpct(Full_20082015a$Neigh_involve_w)

?wpct
?table
?prop.table
?factanal

Labour_labels

```


